language: python

python:
  - "3.9"

before_install:
  - mv travis_secrets.yaml secrets.yaml
  #- sudo apt-get install -y libudev-dev

install:
  - pip3 install homeassistant
  - mkdir custom_components
  - ls
  - git clone https://github.com/youdroid/home-assistant-sickchill sickchill/
  - mv sickchill/custom_components custom_components

script:
  - hass -c . --script check_config --info all

# blocklist
branches:
  except:
  - develop